services:
  drizzle_db_gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle_dateway
    environment: 
      PORT: 4983
      MASTERPASS: your_master_password
      STORE_PATH: /app
      DB: postgres://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    ports: 
      - '4983:4983'
    volumes:
      - drizzle_db_gateway:/app
  db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    container_name: cache
    command: ["redis-server", "--requirepass", "mycachepassword"]
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

volumes:
  drizzle_db_gateway:
  db_data:
  cache_data:
