name: Webapp

on:
  push:
    paths:
      - '.github/workflows/webapp.yml'
      - 'apps/webapp/**'
      - 'package-lock.json'
  pull_request:
    paths:
      - '.github/workflows/webapp.yml'
      - 'apps/webapp/**'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run check --workspace=@budgetbuddyde/webapp
      # - name: Run tests
      #   run: npm run test --workspace=@budgetbuddyde/webapp

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js webapp
        run: 
          pwd
          npm run build --workspace=@budgetbuddyde/webapp
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp-build
          path: apps/webapp/.next
          retention-days: 7

  release-patch:
    name: Release (Patch)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: release-patch
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ðŸš€ Patch release"

  release-minor:
    name: Release (Minor)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: release-minor
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ðŸš€ Minor release"

  release-major:
    name: Release (Major)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: release-major
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ðŸš€ Major release"
